# travis-ci.org build & test configuration
sudo: required
dist: trusty
#sudo: false
language: python

matrix:
    include:
        - python: 2.7
          env: PYTHON=2.7 ROOT=5.34.32
        - python: 2.7
          env: PYTHON=2.7 ROOT=6.04
        - python: 3.4
          env: PYTHON=3.4 ROOT=5.34.32
        - python: 3.4
          env: PYTHON=3.4 ROOT=6.04 COVERAGE=1

#install: source ci/install.sh
install:
	# Deactivate the travis-provided virtual environment and setup a
	# conda-based environment instead
	- deactivate
	# Install miniconda
	- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
	- export MINICONDA_PATH=/home/travis/miniconda
	- chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH
	- export PATH=$MINICONDA_PATH/bin:$PATH
	- conda update --yes conda
  #- if [ "${TRAVIS_OS_NAME}" == "linux" ]; then wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi 
  #- bash miniconda.sh -b -p $HOME/miniconda
  #- export PATH="$HOME/miniconda/bin:$PATH"
  #- hash -r
  #- conda config --set always_yes yes --set changeps1 no
  #- conda update --yes conda
  - conda info -a # Useful for debugging any issues with conda
  - conda config --add channels http://conda.anaconda.org/NLeSC  
  - conda config --set show_channel_urls yes
  - conda create -q -n testenv python=${PYTHON} root=${ROOT} numpy nose sphinx
  #- export CONDA_ENV_PATH=$HOME/miniconda/envs/testenv
  - source activate testenv
  - pip install coverage coveralls

script: bash ci/test.sh
after_success:
    - time coveralls

notifications:
    email: false
